### ISSUE TITLE
Improve infra_process_running error handling

### ISSUE THREAD

**Issue by jthurman42** [newrelic/newrelic-client-go#108]
### Description
Infra API appears to return the data that caused an error and a 400 HTTP response for invalid config of `infra_process_running`, which we do not correctly handle.

### Current behavior
The newrelic-client-go attempts to unmarshal the JSON into an int, which does not work.

### Expected behavior
Concise error returned to the caller.

### References or Related Issues

Reported in [here](https://github.com/terraform-providers/terraform-provider-newrelic/issues/326) on the Terraform provider.

**Comment by zlesnr** [comment]
I did a bit of digging on this one, and the unmarshal error is coming from the API.  This particular API doesn't do any validation on the way in, and I think its converted to a string for storage.  When a call to retrieve the value, the api tries to marshal the object and fails, so returns the error to the caller in this code, which we then add the request status code to and return to our caller.  I hear there are plans to replace this API in the near future, so perhaps this could get fixed when we implement the replacement API.  Not quite sure what to do about it until then.
