### ISSUE TITLE
Gain consistency about time types in Alert objects

### ISSUE THREAD

**Issue by StephenWeber** [newrelic/newrelic-client-go#121]
### Objective
Three Alerts objects have time-like fields, but are represented in two different ways. These should ideally be the same way, my preference is for them all to be plain `int` types, discussed below.

**Incident** has OpenedAt and ClosedAt timestamp fields represented by an `int`: https://github.com/newrelic/newrelic-client-go/blob/8eda621a6ecad4b1808bfe742939eefa8ad7426d/pkg/alerts/alerts_types.go#L86-L87

**InfrastructureCondition** has CreatedAt and UpdatedAt represented by the internal `*serialization.EpochTime` (a redeclaration of `time.Time`): https://github.com/newrelic/newrelic-client-go/blob/8eda621a6ecad4b1808bfe742939eefa8ad7426d/pkg/alerts/alerts_types.go#L101-L113

**Policy** has CreatedAt and UpdatedAt represented by the internal `*serialization.EpochTime` (a redeclaration of `time.Time`): https://github.com/newrelic/newrelic-client-go/blob/8eda621a6ecad4b1808bfe742939eefa8ad7426d/pkg/alerts/alerts_types.go#L174-L175 (these are also pointers, which is fine, it can stay that way for representing optional fields)

### Acceptance Criteria
- These ideally should be the same type
- I'd prefer them being plain `int`s, possibly with helper functions on the type to translate to `time.Time` for other uses like displaying to humans.
- An additional improvement would be changing the Incident.ClosedAt field to be a pointer to reflect its optionality rather than being Epoch `0` (January 1, 1970)

Will comment below on the specific application I'm working on and why I'd prefer `int` types, happy to have the conversation in squaring it with other uses of this library.

**Comment by StephenWeber** [comment]
We're using these alert types in a Kubernetes Operator that will manage alert configuration for services. We'd love to simply reuse the API interface defined by `newrelic-client-go` instead of duplicating the Go struct definitions by hand.

To serialize these structs across JSON and YAML, Kubernetes enforces extra requirements, such as `DeepCopy` and `DeepCopyTo` methods defined on the types in question. I'm trying to generate these methods for the client alerts objects using the `controller-gen` tooling that Kubernetes provides for its project template toolchain [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder). This works great for most of the structs in alerts_types, but it explicitly does _not_ support `time.Time` types of all kinds.

I'm hoping that we could use `int` types for these timestamps, and other uses (like [terraform-provider-newrelic](https://github.com/terraform-providers/terraform-provider-newrelic)) could use type-conversion if they're needed for comparisons or human-legibility.

**Comment by jthurman42** [comment]
@ctrombley what was the initial reason for the serialization package here? I'm sure this is a breaking change for terraform-providers/terraform-provider-newrelic so we'll need to coordinate in either direction we take.

**Comment by StephenWeber** [comment]
In speaking with @ctrombley we worked out:

- purpose of the serialization package was to ensure consistent serialization/deserialization of date types
- the support needed for Kubernetes could be accomplished by augmenting the serialization package, so converting everything to `int` is not necessary

Likely all time values should be converted to the `EpochTime` type, when it's convenient to do so. My work can continue regardless of type, so for my purposes this issue is closed.
