### ISSUE TITLE
Pre-v1 refactoring suggestions

### ISSUE THREAD

**Issue by ctrombley** [newrelic/newrelic-client-go#130]
RFC feedback from Douglas Camata:

I miss having some constants when creating alerts (condition and policies) to have type safety.
For example, to create an alert policy I need to keep in mind that IncidentPreference has its own set of possible values. This is completely hidden in the client’s code.

Normally, what we use to do in our team is to create a type alias and initialize some variables from this type. 

This is how I would personally improve this:

```go
package alerts

type IncidentPreference string

// The name of this constant is debatable, this is only an example.
const IncidentPreference_PER_POLICY = IncidentPreference("PER_POLICY") 

type Policy {
    IncidentPreference IncidentPreference
}
```
With this kind of code, your IDE of choice will smartly give you autocomplete suggestion that make sense when you are creating a variable of type Policy and settings its IncidentPreference field. (edited) 

The same applies for other ENUM-like things, like the region.

Also missed the usage of the type url.URL to have more compile time checks of strings that are URLs.

I also wonder why the type of ViolationCloseTimer in alerts.NrqlCondition isn’t of type time.Duration instead of integer?

**Comment by sanderblue** [comment]
100% on board with these suggestions. I've always done similar things in TypeScript to ensure type correctness, compile-time validation, and IDE autocomplete.
