### ISSUE TITLE
Feature Request: Multi-location failure synthetics alerts

### ISSUE THREAD

**Issue by sanderblue** [newrelic/newrelic-client-go#152]
Downstream feature request: **terraform-provider-newrelic** [#425](https://github.com/terraform-providers/terraform-provider-newrelic/issues/425)

**REST v2 API Explorer:** 
- https://rpm.newrelic.com/api/explore/alerts_location_failure_conditions/create

From the downstream request:

> New Relic Provides creation of multi location failures. The current synthetic alert resource allows for creation of single location failure.
> 
> Documentation Source - https://docs.newrelic.com/docs/alerts/new-relic-alerts/defining-conditions/multi-location-synthetics-alert-conditions
> 
> ![image](https://user-images.githubusercontent.com/44437783/75539945-f3b43f80-59cf-11ea-93f8-6a050b871004.png)
> 
> This is a different endpoint than the single failure synthetic alert - https://api.newrelic.com/v2/alerts_location_failure_conditions/{id}.json
> 
> Request json
> 
> `'{
>   "location_failure_condition": {
>     "name": "string",
>     "runbook_url": "string",
>     "enabled": "boolean",
>     "entities": [
>       "string"
>     ],
>     "terms": [
>       {
>         "priority": "string",
>         "threshold": "integer"
>       }
>     ],
>     "violation_time_limit_seconds": "integer"
>   }
> }' `
>

**Comment by ctrombley** [comment]
This work was completed in #118.
