### ISSUE TITLE
GoDoc overview info

### ISSUE THREAD

**Issue by jthurman42** [newrelic/newrelic-client-go#183]
### Objective
The overview documentation page is too sparse.

### Acceptance Criteria
- The landing page for [GoDoc](https://godoc.org/github.com/newrelic/newrelic-client-go) contains information about the project
- The new Golang doc site for this package is more useful: https://pkg.go.dev/github.com/newrelic/newrelic-client-go?tab=subdirectories

**Comment by ctrombley** [comment]
Resolved by #188
