### ISSUE TITLE
Following README.md File Instructions Results in Failure to Compile App

### ISSUE THREAD

**Issue by colinbjohnson** [newrelic/newrelic-client-go#225]
### Description
When following the instructions contained within the `README.md` file within this repository an error is thrown.

### Go Version
`go version go1.14.1 darwin/amd64`

### Current behavior
When copying/pasting the example in `README.md` and running, the following occurs.

```
colinjohnson@cjohnson07 newrelic_api_connector % go run newrelic_api_connector.go
# command-line-arguments
./newrelic_api_connector.go:9:2: imported and not used: "github.com/newrelic/newrelic-client-go/pkg/config"
./newrelic_api_connector.go:14:5: assignment mismatch: 1 variable but newrelic.New returns 2 values
./newrelic_api_connector.go:14:21: undefined: ConfigAPIKey
```

### Expected behavior
When copying/pasting the example in `README.md` it is expected that the example will run properly (including connecting to NewRelic and, potentially, printing a list of NewRelic applications.

### Steps To Reproduce
1. Copy the text from `README.md` into a `.go` file.
2. Run the command `go run filename.go`
3. The result is a file that is not able to be compiled.

### Debug Output (if applicable)
NA.

### Additional Context
This occurs with the following newrelic-go-client: `github.com/newrelic/newrelic-client-go v0.19.0`.

I've been running with a configuration that looks as follows:

```
package main

import (
	"fmt"
	"os"

	"github.com/newrelic/newrelic-client-go/newrelic"
	"github.com/newrelic/newrelic-client-go/pkg/apm"
)

func main() {
	apiKey := os.Getenv("NEW_RELIC_API_KEY")
	nr, _ := newrelic.New(newrelic.ConfigAdminAPIKey(apiKey))

	params := apm.ListApplicationsParams{
		Name: "RPM",
	}

	apps, err := nr.APM.ListApplications(&params)

	if err != nil {
		fmt.Print(err)
	}

	fmt.Printf("%#v\n", apps)

}
```

I believe the sample code I've written is not ideal because the configuration does not reflect the different methods of providing API Keys to a NewRelic API client - either a ConfigPersonalAPIKey or a ConfigAdminAPIKey - I simply assume the user is providing an environment variable named `NEW_RELIC_API_KEY`.

### References or Related Issues
Are there any other related GitHub issues (open or closed) or Pull Requests that should be linked here?

**Comment by jthurman42** [comment]
Thanks @colinbjohnson for the issue, and a example solution.  I added a few error statements for context too.

**Comment by colinbjohnson** [comment]
Just tested!!! Thank you!
