### ISSUE TITLE
Migrate Types

### ISSUE THREAD

**Issue by sanderblue** [newrelic/newrelic-client-go#23]
### Objective
Migrate [types.go](https://github.com/paultyng/go-newrelic/blob/master/api/types.go) from `go-newrelic` to our project.

Consider whether or not we should put types within their specific domain instead of having all of the types in a single file, which is how `go-newrelic` has done it. Something like `alert_channels_types.go` and `dashboard_types.go` could be a design pattern worth discussing. What advantages/disadvantages would this introduce?

### Acceptance Criteria
- Migrate the code and make any reasonable updates to the implementation pattern
    - Note: The design pattern should be agreed upon by the dev team and should be consistent with all other features/resources
- Include tests

**Comment by jthurman42** [comment]
@sanderblue Has this been answered?

**Comment by sanderblue** [comment]
Yes, we went with the pattern of `{resource}_types.go` for the time being.
