### ISSUE TITLE
[Request] Go structs for GraphQL responses

### ISSUE THREAD

**Issue by skyzyx** [newrelic/newrelic-client-go#246]
### Feature Description

So… GraphQL is cool and interesting stuff. I love it. I've built with it. It's great. But I was reviewing this SDK, and saw the following code block in [one of the examples](https://pkg.go.dev/github.com/newrelic/newrelic-client-go@v0.20.1/pkg/nerdgraph?tab=doc):

```go
resp, err := client.Query(query, variables)
if err != nil {
	log.Fatal("error running NerdGraph query: ", err)
}

queryResp := resp.(QueryResponse)
actor := queryResp.Actor.(map[string]interface{})
account := actor["account"].(map[string]interface{})
nrql := account["nrql"].(map[string]interface{})
results := nrql["results"].([]interface{})
```

IMO, this is gross. I most often see this when JSON/TOML/YAML has been unmarshaled into an `interface{}` type and the rest of us poor souls have to do a bunch of typecasting to get what we want.

I'm not sure if you guys have internal models for your APIs like AWS and Google do, but they're really great for code generation and enabling same-day SDK updates as the APIs release. They're also really great at generating Go structs for JSON responses.

And that is my request. Providing Go structs for all of the response models represented in the GraphQL API. The model data is internal to New Relic and — now that I think about it — you may be able to use the GraphQL schemas themselves to generate the Go structs.

I believe that this would provide a _much_ improved user experience for the SDK. Thank you.

**Comment by zlesnr** [comment]
Hi @skyzyx, thanks for raising the issue.

The nergraph package in particular is the piece that communicates with our GraphQL API, as you've discovered, but each of the various packages support a specific product, and those are starting to shape up.

https://github.com/newrelic/newrelic-client-go/tree/master/pkg

We're starting to make inroads towards code generation for those packages as well, which you can review here:  https://github.com/newrelic/newrelic-client-go/tree/master/tools/typegen

Is there a particular product that you are looking to integrate with first?

Cheers.

**Comment by skyzyx** [comment]
My company has recently kicked off a massive migration from our previous vendor over to New Relic. 100s of our applications are coming over.

My team supports a Monitoring-as-Code CLI application which accepts a configuration file from a number of teams and based on that data, the application will automate the generation of Terraform code which uses the New Relic provider. Anything that the Terraform provider does not support, I am filling in the blanks with the SDK.

For applications to set up their monitoring before our monitoring as code solution became available, I’m using [Terraformer](https://github.com/GoogleCloudPlatform/terraformer) to export whatever data I can from our previous vendor and using Hashicorp’s HCL package to try to generate new `.tf` files which use the New Relic provider (although it’s not a 1:1 conversion).

So…

I started exploring this SDK yesterday and wanted to kick the tires to understand its maturity, the types of patterns it uses, etc. All of the core stuff (APM, Infrastructure, Browser, Synthetics, Insights, and some of the NR1 features that I’m not as familiar with yet) will be used. As well as how New Relic integrates with other services (CloudWatch, Slack, PagerDuty).

If you guys are working on building out Go structs so that engineers like me don’t have to type `map[string]interface{}` a jillion extra times, then we’re cool. I understand that things are moving rapidly and the GraphQL stuff you’re building is very new. :)

I just couldn’t tell from the example code how much extra typecasting I would have to do based on the 0.x version of this package.

Thanks!

**Comment by zlesnr** [comment]
Thank you for your interest here, and for the context about your environment.  If you're curious about what else we've got coming up, our roadmap is pretty up to date: https://newrelic.github.io/developer-toolkit/roadmap/

This repo is now backing the Terraform provider entirely, and we're starting to shift some of the calls to graphql currently.   This repo also backs a CLI that we're working on for a few fill-in-the-gap sort of features: https://github.com/newrelic/newrelic-cli

We'd welcome feedback as it comes up.

Cheers.

**Comment by skyzyx** [comment]
Excellent to hear. Thank you.
