### ISSUE TITLE
Add support for Insights API

### ISSUE THREAD

**Issue by sanderblue** [newrelic/newrelic-client-go#310]
### Feature Description
The [go-insights](https://github.com/newrelic/go-insights) client + CLI supports the [Insights API](https://docs.newrelic.com/docs/insights/insights-api). It could be potentially beneficial to include this functionality in the client so that other applications can utilize it, such as **newrelic-cli**.

This ticket is loosely related to a [request that was submitted](https://github.com/newrelic/go-insights/issues/16) in go-insights.

**Comment by jthurman42** [comment]
Query side of this was implemented in #345
