### ISSUE TITLE
Scrub known-sensitive values from logging

### ISSUE THREAD

**Issue by jthurman42** [newrelic/newrelic-client-go#327]
### Objective
Currently sensitive values are logged at the TRACE level including API keys.  We should scrub / filter these fields from the logs.

Known areas:
- [HTTP Request logging](https://github.com/newrelic/newrelic-client-go/blob/master/internal/http/client.go#L203)

### Acceptance Criteria
- Sensitive fields are identified and documented as such (GoDoc)
- Sensitive fields do not appear at high levels of logging

**Comment by sanderblue** [comment]
We should also add a snippet in the documentation warning users that sensitive data _could_ be within logs when using TRACE level logging, such as creating certain notification channels.

**Comment by zlesnr** [comment]
Related to https://github.com/newrelic/newrelic-client-go/pull/424
