### ISSUE TITLE
Add unit test helpers for mocking

### ISSUE THREAD

**Issue by sanderblue** [newrelic/newrelic-client-go#34]
### Objective
To facilitate better test coverage and ease of writing tests, we need a some helper functions to help create generic mocks.

### Acceptance Criteria
- Create helper method to mock application response data
- TBD

**Comment by jthurman42** [comment]
This should be a fast-follow after #82

**Comment by jthurman42** [comment]
Resolved in #88 Though not completely implemented across all tests.
