### ISSUE TITLE
Nerdgraph NRQL Conditions are using incorrect operator types for Outlier and Baseline

### ISSUE THREAD

**Issue by zlesnr** [newrelic/newrelic-client-go#368]
### Description
Currently, the three types of NRQL conditions are sharing an object for "Terms".  From Nerdgraph, we're using `AlertsNrqlConditionTermsOperator` for all three types of NRQL conditions, where the Baseline and Outlier should be using `AlertsNrqlDynamicConditionTermsOperator`.  The difference is that the later only supports the `ABOVE` value, at the time of this writing.  This currently means that for users making use of Outlier and Baseline NRQL conditions need to ensure they are passing the right data, or the error will be returned to the user from the call, rather than at compile time.

**Comment by zlesnr** [comment]
https://github.com/newrelic/newrelic-client-go/pull/369

**Comment by sanderblue** [comment]
Resolved in #369
