### ISSUE TITLE
Renaming a project in Go breaks everything that relies on it

### ISSUE THREAD

**Issue by zbintliff** [newrelic/newrelic-client-go#371]
Previous project was: github.com/newrelic/go-agent
This project now returns a 404

new project is https://github.com/newrelic/newrelic-client-go

ANY golang project that relies the go-agent is now broken.

**Comment by zlesnr** [comment]
Hi @zbintliff, thank you for the report.  I don't think this is quite right, though.  This repo wasn't renamed to my knowledge, and looking in the history, seems to confirm this.  But to dig in to the root of your issue, I don't know where that repo went.  I have a checkout of it locally, but I've not fetched in well over a year, so can't confirm the status.  It does look like the repo is back now, perhaps they were just moving things around.  Let me know if I can help further.

**Comment by zbintliff** [comment]
You're right, I just assumed it was renamed. I worked with NR support to fix and restore the original repo. 

Thanks!
