### ISSUE TITLE
Custom Events sent with Batch Event API not showing up in Insights: Data Explorer (NRQL)

### ISSUE THREAD

**Issue by skyzyx** [newrelic/newrelic-client-go#464]
## Description

Batch custom events don't appear to be pushing out to New Relic. I am attempting to use the process documented in “[Use the Event API to report custom events](https://docs.newrelic.com/docs/telemetry-data-platform/ingest-manage-data/ingest-apis/use-event-api-report-custom-events)”.

1. I have a Go app who's job is to read some profiling data, parse it, and push it up into New Relic as _custom events_.

1. I'm using goroutines to spread different types of profiling tasks (with different data) for concurrency.

1. Inside each goroutine, I read the profiling data, parse it, and , and push it up into New Relic as _custom events_ using the [`Events.BatchMode`](https://pkg.go.dev/github.com/newrelic/newrelic-client-go@v0.40.0/pkg/events?tab=doc#Events.BatchMode) SDK API.

In the (attempted) chart below: sibling nodes happen concurrently; child nodes are sequential. The _batch → enqueue → flush_ steps are happening with the New Relic SDK.

```plain
main()
├── routine-1
│   └── read
│       └── parse
│           └── batch
│               └── enqueue
│                   └── flush (then respond to channel, then close the channel)
│
├── routine-2
│   └── ...
│
└── routine-3
    └── ...
```

I am operating with the assumption that the New Relic SDK is automatically handling constraints such as [payload sizes](https://docs.newrelic.com/docs/insights/insights-data-sources/custom-data/insights-custom-data-requirements-limits).

## Go Version

```plain
go version go1.15.1 darwin/amd64
```

## Current behavior

After running my program, testing for SDK errors and not finding any, I attempt to lookup my custom metrics using _Insights: Data Explorer_ and cannot find it.

Based on “[Find my data](https://docs.newrelic.com/docs/telemetry-data-platform/ingest-manage-data/ingest-apis/use-event-api-report-custom-events#find-data)”, I am not seeing my `eventType` name when I use Insights to query NRQL for:

```sql
FROM {my-eventType} SELECT *
```

## Expected behavior

I expect to be able to lookup my custom metrics using _Insights: Data Explorer_ and find them. Based on “[Find my data](https://docs.newrelic.com/docs/telemetry-data-platform/ingest-manage-data/ingest-apis/use-event-api-report-custom-events#find-data)”, I expect to see my `eventType` name when I use Insights to query NRQL for:

```sql
FROM {my-eventType} SELECT *
```

## Steps To Reproduce

1. I am receiving batches of records from an upstream service, wherein each individual record looks something like this:

    ```json
    {
      "path": [
        "widget-data",
        "epub",
        "sn_206a-ddfdc8b5efa746eab698dad884f08979",
        "user:urn:************"
      ],
      "unIndexed": false,
      "millis": 1,
      "pendingTime": 0,
      "bytes": 0,
      "client": {
        "remoteAddress": {
          "address": "2605:****:****:****:****:****:****:c2bc"
        },
        "userAgent": {
          "browser": "chrome",
          "os": "os_x",
          "platform": "desktop",
          "userAgentString": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36",
          "version": "85"
        }
      },
      "allowed": true,
      "name": "listener-listen",
      "timestamp": 1599693720596
    }
    ```

2. I'm unmarshaling that JSON structucture into the following Go structs:

    ```go
    type RawShape struct {
      Allowed        bool           `json:"allowed"`
      UnIndexed      bool           `json:"unIndexed"`
      Bytes          int64          `json:"bytes"`
      ClientsUpdated int64          `json:"clientsUpdated"`
      Millis         int64          `json:"millis"`
      PendingTime    int64          `json:"pendingTime"`
      Timestamp      int64          `json:"timestamp,omitempty"`         // Measured in milliseconds since Epoch
      FBTimestamp    int64          `json:"firebaseTimestamp,omitempty"` // Measured in milliseconds since Epoch
      Name           string         `json:"name"`
      EventType      string         `json:"eventType,omitempty"` // Required by New Relic for the event to go through
      Path           []string       `json:"path,omitempty"`
      Client         RawShapeClient `json:"client,omitempty"`
    }

    // RawShapeClient is part of the response from the Firebase Profiler.
    type RawShapeClient struct {
      RemoteAddress RawShapeClientRemoteAddress `json:"remoteAddress,omitempty"`
      UserAgent     RawShapeClientUserAgent     `json:"userAgent,omitempty"`
    }

    // RawShapeClientRemoteAddress is part of the response from the Firebase Profiler.
    type RawShapeClientRemoteAddress struct {
      Address string `json:"address,omitempty"`
    }

    // RawShapeClientUserAgent is part of the response from the Firebase Profiler.
    type RawShapeClientUserAgent struct {
      Browser         string `json:"browser,omitempty"`
      Os              string `json:"os,omitempty"`
      Platform        string `json:"platform,omitempty"`
      UserAgentString string `json:"userAgentString,omitempty"`
      Version         string `json:"version,omitempty"`
    }
    ```

3. I have a function which performs the processing and sends data to New Relic:

    ```go
    // "github.com/newrelic/newrelic-client-go/pkg/config"
    // "github.com/newrelic/newrelic-client-go/pkg/events"

    func profileRaw(c chan Response) {
        ctx := context.Background()

        // New Relic Account ID must be passed as an integer
        nrAccountID, err := strconv.Atoi(os.Getenv("NEWRELIC_ACCOUNT_ID"))
        if err != nil {
            log.Fatalln(err)
        }

        // Run the profiler
        output, ok := getProfilerData() // batches of JSON records as a string (see above)
        if !ok {
            log.Fatalln("Profiler failed.")
        }

        payloads := strings.Split(output, "\n\n")

        // Instantiate the New Relic client
        cfg := config.New()
        cfg.InsightsInsertKey = os.Getenv("NEWRELIC_INSIGHTS_INSERT")
        cfg.Compression = config.Compression.Gzip

        client := events.New(cfg)

        // Start batch events mode
        if err := client.BatchMode(
            ctx,
            nrAccountID,
            events.BatchConfigQueueSize(50),
            events.BatchConfigTimeout(10*int(time.Second)),
        ); err != nil {
            log.Fatalln("error starting batch mode:", err)
        }

        for i := range payloads {
            payload := payloads[i]
            event := RawShape{}

            // Read the JSON into the appropriate Go struct
            err = json.Unmarshal([]byte(payload), &event)
            if err != nil {
                log.Fatalln(err)
            }

            // Required by New Relic for the event to go through
            event.EventType = "ProfilerRaw"

            // Timestamp is a reserved word <https://j.mp/3bMspEb>
            event.FBTimestamp = event.Timestamp
            event.Timestamp = 0

            // Queue a custom event
            if err := client.EnqueueEvent(ctx, event); err != nil {
                log.Fatalln("error posting custom event:", err)
            }
        }

        // Force-flush the events when we're done with this batch of data so that
        // the function ends and returns instead of listening indefinitely.
        if err := client.Flush(); err != nil {
            log.Fatal("error flushing event queue:", err)
        }

        // Prepare to close the channel
        defer wgRawData.Done()

        // Return data to the channel, closing it
        c <- resp // This references measurement data that I removed from this report.
    }
    ```

4. A sample of event data that gets sent over the wire looks _similar_ to the JSON example above. Replaced `timestamp` with `firebaseTimestamp`, added an `eventType` key, and keys are in a different order.

    ```json
    {
      "allowed": true,
      "unIndexed": false,
      "bytes": 0,
      "clientsUpdated": 0,
      "millis": 1,
      "pendingTime": 0,
      "firebaseTimestamp": 1599693720596,
      "name": "listener-listen",
      "eventType": "ProfilerRaw",
      "path": [
        "widget-data",
        "epub",
        "sn_206a-ddfdc8b5efa746eab698dad884f08979",
        "user:urn:************"
      ],
      "client": {
        "remoteAddress": {
          "address": "2605:****:****:****:****:****:****:c2bc"
        },
        "userAgent": {
          "browser": "chrome",
          "os": "os_x",
          "platform": "desktop",
          "userAgentString": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36",
          "version": "85"
        }
      }
    }
    ```

## Debug Output (if applicable)

No errors in any of the error handling above.

## Context

1. I am not seeing any correlating events when running:

    ```sql
    SELECT count(*) FROM NrIntegrationError SINCE 12 HOURS AGO COMPARE WITH 1 WEEK AGO TIMESERIES
    ```

2. Yes, I have confirmed that the environment variables are set with correct data.

3. Yes, I have confirmed that I'm pushing data into the correct NR Account ID.

**Comment by zlesnr** [comment]
Thank you for the report.  Just confirming, have you pushed at least 50 items into the queue?  Also, for the query (its been a while since I was batching events) but I think the table should be `ProfilerRaw` based on `event.EventType = "ProfilerRaw"
` correct?  Or do I have that wrong?

Also, when flushing, do you see the log message `flushing events`?  Perhaps we could include the count of items that are flushing there just so we have some indication of the queue size at flush time.

**Comment by skyzyx** [comment]
Hey Zach, thanks for responding.

> Just confirming, have you pushed at least 50 items into the queue?

I'm recording about 89 records going in for this particular test. (Just trying to get it working before I turn it on for real.)

> Also, for the query (its been a while since I was batching events) but I think the table should be ProfilerRaw based on event.EventType = "ProfilerRaw" correct? Or do I have that wrong?

Not sure. This is my first time working with custom events, so I'm going on what I'm reading in the docs (which I've linked, above). Would love some direction here.

> Also, when flushing, do you see the log message flushing events? Perhaps we could include the count of items that are flushing there just so we have some indication of the queue size at flush time.

I wasn't seeing any messages logged from the SDK. I was going to look at that next. I saw that there is a `config.Config` object that has a `Logger` key, but I hadn't done anything with that next. Also (not sure if it matters), but I intend to run this in AWS Lambda, so I'm performing my testing in the `go1.x` Docker image from https://github.com/lambci/docker-lambda. I have not yet confirmed whether or not it eats messages sent to `os.Stdout` or `os.Stderr`.

**Comment by zlesnr** [comment]
I think `cfg.LogLevel = "debug"` before you create the client or some such might help you there.

https://github.com/newrelic/newrelic-client-go/blob/9e8c090fa520210a5f17b746f5d9c8c01e7c5030/pkg/config/config.go#L50

I would expect those 89 events to have shipped then, but let's enable debug and see if we have those messages.

**Comment by skyzyx** [comment]
Setting it to `trace`, I'm seeing messages like the following (account ID redacted):

```
DEBU[0022] performing request                            method=POST url="https://insights-collector.newrelic.com/v1/accounts/{account-id}/events"
DEBU[0022] flushing events
DEBU[0022] performing request                            method=POST url="https://insights-collector.newrelic.com/v1/accounts/{account-id}/events"
DEBU[0022] Timeout expired, flushing queued events
DEBU[0022] flushing events
DEBU[0022] Timeout expired, flushing queued events
DEBU[0022] flushing events
DEBU[0022] Timeout expired, flushing queued events
DEBU[0022] flushing events
```

If the POST were to fail for whatever reason, I would expect an error message to bubble up somewhere. This would suggest that data is making its way over, but… perhaps I'm not querying it correctly?

**Comment by zlesnr** [comment]
At a minimum, seems like those log messages should be more informative, your right that the errors would have show up if the post failed.  Did you try `SELECT count(*) FROM ProfilerRaw ...` too?

**Comment by skyzyx** [comment]
> Did you try `SELECT count(*) FROM ProfilerRaw ...` too?

I did. It doesn't understand `ProfilerRaw`. It's also not showing up in the Data Explorer. https://insights.newrelic.com/accounts/{account-id}/explorer

Just to confirm — the `eventType` field at the root of my JSON event should match the `FROM` value, right?

**Comment by zlesnr** [comment]
That's probably right.  What I'm not seeing is where the table is getting specified so that you know where to issue the query.

**Comment by skyzyx** [comment]
If the events are getting rejected on the NRDB side, is there any way to see details there? The `NrIntegrationError` table doesn't give me very much information, and even then, I'm having trouble correlating the timestamps to see if that's an issue.

**Comment by skyzyx** [comment]
Ah… from https://docs.newrelic.com/docs/telemetry-data-platform/ingest-manage-data/ingest-apis/use-event-api-report-custom-events#instrument

> **Data types**
>
> The API only accepts key-value pairs, not map/object or array values. Supported data types for this API are strings and numbers (integers or floats). For more information, see [Data requirements](https://docs.newrelic.com/docs/insights/insights-data-sources/custom-data/insights-custom-data-requirements-limits).

Could this mean that I need to go through and flatten my payload? I was operating with the assumption that the SDK would automatically convert map keys to period-delimited strings. I also seem to have an `[]string` type which may be causing trouble.

Let me poke at those to see if I get anywhere.

**Comment by skyzyx** [comment]
> I was operating with the assumption that the SDK would automatically convert map keys to period-delimited strings.

It does not appear that the SDK is doing anything to handle structs that are not just flat key/value pairs. It only throws an error on the `json.Marshal` if there's an error there.

https://github.com/newrelic/newrelic-client-go/blob/2b496d434f33085b28e4adc93a8efa5f3d87cb00/pkg/events/events.go#L93

Also, it would appear that none of the tests cover complex structures either.

https://github.com/newrelic/newrelic-client-go/blob/2b496d434f33085b28e4adc93a8efa5f3d87cb00/pkg/events/events_integration_test.go#L28-L51

https://github.com/newrelic/newrelic-client-go/blob/2b496d434f33085b28e4adc93a8efa5f3d87cb00/pkg/events/example_basic_test.go#L22-L28

https://github.com/newrelic/newrelic-client-go/blob/2b496d434f33085b28e4adc93a8efa5f3d87cb00/pkg/events/example_batch_test.go#L28-L34

I think that the SDK is just passing my complex structure through as JSON, and it's being rejected on the NRDB side.

**Comment by zlesnr** [comment]
Good catch, I think you're right.  Perhaps that could be a reason to accept a `map[string]interface{}` or warn when the data received is not of key/value format.  I'm not quite sure what the right UX there is.

**Comment by skyzyx** [comment]
My recommendation would probably be the inverse (although I admittedly haven't thought through all of the developer use-cases the way you probably have).

I would recommend _accepting_ nested maps, then using something like https://github.com/jeremywohl/flatten to automatically flatten it into a structure with period-delimited keys.

This solution doesn't address (a) reserved words for JSON keys, or (b) arrays/list values, though.

**Comment by skyzyx** [comment]
This doesn't appear to be an issue with the SDK. Rather, it appears to be an issue with NRDB dropping data on injestion.

I'm going to escalate through New Relic Support and our Account Manager.

Thanks!
