### ISSUE TITLE
Support for Applied Intelligence: Incident Workflows

### ISSUE THREAD

**Issue by skyzyx** [newrelic/newrelic-client-go#466]
### Feature Description

Please add support for [Applied Intelligence: Incident Workflows](https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/enhance-notifications-incident-workflows) (beta).

### Additional context

We're being asked to migrate from [New Relic Connect](https://blog.newrelic.com/product-news/introducing-new-relic-connect-making-life-easier-for-our-customers-partners/) over to [Applied Intelligence: Incident Workflows](https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/enhance-notifications-incident-workflows) (beta) in short order (probably still during the beta period).

Since we practice _monitoring-as-code_, it's important to us that we be able to drive this migration using Terraform (greatly preferred) or via this SDK. We have too many applications and pre-existing implementations of New Relic Connect to be able to think about doing them by-hand via the UI.

Blocking https://github.com/newrelic/terraform-provider-newrelic/issues/873

**Comment by skyzyx** [comment]
Was speaking to our New Relic Account Manager recently about the fact that WARN thresholds on alerts don't trigger notification channels. She said:

> “The warning notifications can be done through Incident Intelligence today. In IINT through pathways you can specify to send just WARNINGS.”

Is this the same thing as what this ticket is for?

**Comment by NSSPKrishna** [comment]
Closing this issue, as this is released in the version 0.90.0.
