### ISSUE TITLE
Document supported Go versions

### ISSUE THREAD

**Issue by zlesnr** [newrelic/newrelic-client-go#474]
### Objective

Here we seek to provide users of this project information about which versions of Go are supported.

Currently, the `go.mod` references `1.13`, and the tests look to be using `1.14`.  

### Acceptance Criteria
- Determine supported versions.  `v1.13+`?
- Document the supported versions in the README.
- Determine if the test suite needs to change to include the supported versions.

**Comment by skyzyx** [comment]
The Go core team supports _current_ and _current - 1_. As of today, that's 1.14 and 1.15. https://golang.org/s/release

Not saying you should copy them, but technically, Go 1.13 is EOL and doesn't receive security patches anymore.
