### ISSUE TITLE
Support for Query Insights API

### ISSUE THREAD

**Issue by geototti21** [newrelic/newrelic-client-go#483]
### Feature Description
I was trying to use this library to Query the [Insights API](https://docs.newrelic.com/docs/insights/insights-api/get-data/query-insights-event-data-api) but it doesn't seem to be a way to do it. I could see that you supported this in the [old library](https://github.com/newrelic/go-insights), any plans to introduce it this library as well?

**Comment by ctrombley** [comment]
Hi @geototti21, NRQL queries can already be performed by this client.  See [here](https://github.com/newrelic/newrelic-client-go/blob/master/pkg/nrdb/example_query_test.go) for an example.

**Comment by geototti21** [comment]
👋 hey @ctrombley, thanks for that! I was looking for "Query Insights" but looks like this is named differently now using the GraphQL server! Thanks for pointing this out 🙌
