### ISSUE TITLE
Spike: Plan + document primary client features + responsibilities

### ISSUE THREAD

**Issue by sanderblue** [newrelic/newrelic-client-go#5]
We need a high-level overview of the primary features and responsibilities that the client should incorporate. 

Starting point:
- Include all current capabilities in `paultyng/go-newrelic`
- Include all current capabilities in `dollarshaveclub/new-relic-synthetics-go`

Some preliminary questions:
- Will this project contain **_the_** CLI?
- How does Terraform fit into the mix?
    - Currently `terraform-provider-newrelic` leverages `paultyng/go-newrelic` and `dollarshaveclub/new-relic-synthetics-go`. If we include a CLI in this project, will we include Terraform features in it?
- Will this project contain more than one package? 
    - If so, what will those packages be? (This ties directly to project architecture)
- What additional 3rd party integrations are worthy of being included, if any?
    - i.e. [CloudFormation](https://aws.amazon.com/cloudformation/)
- Super long term question: Do New Relic **Logs** come into play for this project?

**Comment by jthurman42** [comment]
@sanderblue I believe this has also been completed.

**Comment by sanderblue** [comment]
Agreed 🙂
