### ISSUE TITLE
Review http paging parser logic

### ISSUE THREAD

**Issue by jthurman42** [newrelic/newrelic-client-go#56]
### Objective
Currently, we pass the entire response body to the internal `http` client to for page handling.  If the responses are particularly large, that is a bunch of data to pass around.

### Acceptance Criteria
- Paging parser logic is reviewed
- Decision is made if there is to be a refactor
- Refactoring completed if necessary

**Comment by ctrombley** [comment]
Right now there is only one pager implementation, `LinkHeaderPager`.  It's interface, `Pager`, [has a Parse method that accepts a reference to `http.Response`](https://github.com/newrelic/newrelic-client-go/blob/master/internal/http/paging.go#L11).  We are not currently copying large response bodies or anything like that, so I am inclined to leave things as-is.
