### ISSUE TITLE
Infra Alert Conditions: support thresholds with float values

### ISSUE THREAD

**Issue by sanderblue** [newrelic/newrelic-client-go#64]
### Objective
Infrastructure alert condition thresholds can apparently be set to float values via the New Relic UI. Our Go client should support this as well. The type update would happen [here](https://github.com/newrelic/newrelic-client-go/blob/master/pkg/alerts/infrastructure_conditions_types.go#L30).

The original [issue](https://github.com/terraform-providers/terraform-provider-newrelic/issues/291) was reported in the `terraform-provider-newrelic` project.

### Acceptance Criteria
- Infrastructure alert condition thresholds support using float values.

**Comment by jthurman42** [comment]
Resolved in #71
