### ISSUE TITLE
Provide support for Entity Tags

### ISSUE THREAD

**Issue by ctrombley** [newrelic/newrelic-client-go#67]
### Objective
Support the CRUD operations for Entity Tags as provided by Nerdgraph.

### Acceptance Criteria
- Support the entity tag mutations available via Nerdgraph:
  - `taggingAddTagsToEntity`
  - `taggingDeleteTagFromEntity`
  - `taggingDeleteTagValuesFromEntity`
  - `taggingReplaceTagsOnEntity`
- Establish a reusable pattern for implementing additional Nerdgraph functionality
- Take note of how this implementation might be generated via Nerdgraph schema introspection and gather notes and insights to that end.

**Comment by sanderblue** [comment]
Resolved in #95
