### ISSUE TITLE
Decide on a refactoring for "_types.go" files

### ISSUE THREAD

**Issue by ctrombley** [newrelic/newrelic-client-go#68]
### Objective
Provide the cleanest representation of resource types possible for the project.

### Acceptance Criteria
- Decide as a team on the best possible refactoring.  Some options:
  - Provide a `types.go` file per package
  - Move types into their associated resource files
  - None required

**Comment by sanderblue** [comment]
Resolved in this [commit](https://github.com/newrelic/newrelic-client-go/commit/f8eeed496c66a38275061071ef3ae27bf9fe54e4)
