### ISSUE TITLE
Error handling updates needed (deadline of 07/31)

### ISSUE THREAD

**Issue by mattbaker** [newrelic/newrelic-client-go#765]
Nerd Graph's error structure is changing slightly for stitched services. Check the announcements in `#nerdgraph-announcements` for specific details on what's changing and how clients will need to adapt.

Since Nerd Graph is currently breaking spec to ensure backwards compability we'll need to keep this transition window relatively short. We've set a deadline of one month (07/31) for folks to transition.

Someone with more familiarity should probably audit the error handling code to build confidence, but I think I've spotted at least a couple places that will need an update. It'd be best if people with more experience did a quick check as well. More details are in the blog posts posted in the slack channel above.

https://github.com/newrelic/newrelic-client-go/blob/2932f5d6275d9017fd1ce5764d2de258575dd187/pkg/alerts/nrql_conditions.go

This error handling code will break because the downstreamResponse key is going away. Instead, this code should iterate through the errors list and check the "message" value of each error. In other words, drilling down into "downstream response" is not necessary. Error objects formerly in `downstreamResponse` will now be presented directly, with things like error extensions intact. No need to "drill down".

We're not Go experts on Unified API, but maybe the fix could be as simple as this?

```
	for _, err := range r.Errors {
    if strings.Contains(err.Message, "Not Found") {
				return true
			}
	}
```

Note that this would rely on an update to `/internal/http/graphql.go`.

https://github.com/newrelic/newrelic-client-go/blob/2932f5d6275d9017fd1ce5764d2de258575dd187/pkg/alerts/policies.go

This is the same situation as the above. A fix might look something like?

```
for _, err := range r.Errors {
  if err.Message == "Not Found" &&
    err.Extensions.Code == "BAD_USER_INPUT" {
    return true
  }
}
```

Note that this would rely on an update to `/internal/http/graphql.go`.

https://github.com/newrelic/newrelic-client-go/blob/2932f5d6275d9017fd1ce5764d2de258575dd187/internal/http/graphql.go

Errors from downstream services are being merged in with any other errors Nerd Graph sends and the downstreamResponse key will be removed.

This means the list of errors in a Nerd Graph response should be iterated through and this code should check the `extensions` property of each error instead of drilling down into the "downstreamResponse". The "path" can help you identify if a specific error maps to a specific field.

If there are lingering questions after the blog posts, please come find us in our help channel! Unified API wants to make this as pain-free as possible.

**Comment by ctrombley** [comment]
Thanks for the detailed writeup @mattbaker!  We'll make sure to address this soon.

**Comment by mattbaker** [comment]
Holler if we can help or pair on zoom or something!

**Comment by mattbaker** [comment]
Bumpin' for the stale bot since we're a couple weeks from the deadline
