### ISSUE TITLE
Region Constants reference Deprecated API Endpoints

### ISSUE THREAD

**Issue by tcgbrett** [newrelic/newrelic-client-go#844]
### Description
The `restBaseURL` in `pkg/region/region_constants.go` refers to `api.newrelic.com/v2` which is deprecated for Dashboard interaction. That means the whole Dashboards package can't actually interact with the new NerdGraph API.

### Go Version
go version go1.17.2 darwin/amd64

### Current behavior
When I use the dashboards package, the URL points to a deprecated endpoint, so the request fails.
The failure
```
error creating dashboard:410 response returned: This endpoint is deprecated: Please see documentation on migrating to NerdGraph, our GraphQL API, here:, https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/core-concepts/dashboards-api-migration-insights-api-nerdgraph, and check the announcement: https://discuss.newrelic.com/t/important-insights-dashboard-api-end-of-life/149357
```

I changed my local NR code in `pkg/dashboards/dashboard.go` to print what the devised URL is, and it does confirm my suspicions. I changed [this](https://github.com/newrelic/newrelic-client-go/blob/main/pkg/dashboards/dashboard.go#L155) to a print statement
```
	url := d.config.Region().RestURL("dashboards.json")
	log.Println("Built URL: ", url)
```
And it printed: `Built URL:  https://api.newrelic.com/v2/dashboards.json`

### Expected behavior
This should interact with a non-deprecated API so it's usable.

### Steps To Reproduce
Try to use `client.CreateDashboard(*db)` and it will fail.

**Comment by tcgbrett** [comment]
... I would not like this issue closed. I would like if someone from NR responded.

**Comment by michaelprice232** [comment]
This is affecting us as well so would be keen on a fix
