### ISSUE TITLE
Support Node16 runtime for Synthetics

### ISSUE THREAD

**Issue by jaecktec** [newrelic/newrelic-client-go#910]
### Feature Description
`SCRIPT_API` synthetics are create with node10(legacy) but should be create with node16

### Code Example
```
resource "newrelic_synthetics_monitor" "foo" {
  name      = "foo"
  type      = "SCRIPT_API"
  frequency = 5
  status    = "ENABLED"
  locations = var.locations
  runtime = "16" # or maybe 'legacy' if we want to make node16 the default
}
```

### Additional context
For backwards compatibility this should be selectable.

**Comment by kidk** [comment]
I think this is an artifact from using the REST API. There is currently work being done to migrate all Synthetics resources to the GraphQL API, which should always select the latest runtime. 

I'm going to close this ticket, as we're tracking the work here: https://github.com/newrelic/terraform-provider-newrelic/issues/1453
