### ISSUE TITLE
NRQL Drop Rule Getter Function

### ISSUE THREAD

**Issue by tamirFireFly** [newrelic/newrelic-client-go#911]
### Feature Description
Function for GetNRQLDropRule by its id. Currently there is only list function and we need to search

### Describe Alternatives

Currently i use the list and search it.
The list from here
https://github.com/newrelic/newrelic-client-go/blob/main/pkg/nrqldroprules/nrqldroprules_api.go

### Additional context
Also list and get for nrql alert conditions would be nice :)

**Comment by kidk** [comment]
Hi @tamirFireFly thanks for your request.

We don't have a `get` function available in the API so there's no way to implement this. I think the only option is to loop the list to find the right one.

**Comment by kidk** [comment]
@tamirFireFly check out this for NRQL Alert conditions: 
- Get https://github.com/newrelic/newrelic-client-go/blob/main/pkg/alerts/nrql_conditions.go#L387
- List https://github.com/newrelic/newrelic-client-go/blob/main/pkg/alerts/nrql_conditions.go#L355

**Comment by shashank-reddy-nr** [comment]
Hi @tamirFireFly we have added nrql drop Rule by ID function. Please check and make use of it [GetdropRuleByID](https://github.com/newrelic/newrelic-client-go/blob/13afc02e257ec6a108d58365bad8072c8331798c/pkg/nrqldroprules/nrqldroprules_api_.go#L10).
