### ISSUE TITLE
Event Batch Mode Panic

### ISSUE THREAD

**Issue by ctriv** [newrelic/newrelic-client-go#951]
### Description
If Events.BatchMode() is used with a context that finishing (ie, the Done() channel produces a message), there is a panic in a trace log line

### Go Version
go version go1.19.3 darwin/arm64

### Current behavior
Entered batch mode using a cancelable context.  When the context is canceled, a panic is issued.

### Expected behavior
The library should finish cleanly when the context is done.

### Steps To Reproduce
1. Enter batch mode with a cancelable context:
```
ctx, done := context.WithCancel(context.Background())
client.BatchMode(ctx, 123456, ....)
```
2. do work, send events, etc..
```
client.EnqueueEvent(ctx, ....)
```

3. Call done to cancel the context:
```
done()
```
4. Panic
```panic: interface conversion: interface {} is int, not string

goroutine 33 [running]:
github.com/newrelic/newrelic-client-go/v2/pkg/logging.createFieldMap(...)
	/Users/creinhardt/go/pkg/mod/github.com/newrelic/newrelic-client-go/v2@v2.2.2/pkg/logging/logrus_logger.go:101
github.com/newrelic/newrelic-client-go/v2/pkg/logging.LogrusLogger.Trace({0x14000064e78?}, {0x1011c8a72?, 0xc?}, {0x1400055e040?, 0x140006e4201?, 0x0?})
	/Users/creinhardt/go/pkg/mod/github.com/newrelic/newrelic-client-go/v2@v2.2.2/pkg/logging/logrus_logger.go:92 +0x1d8
github.com/newrelic/newrelic-client-go/v2/pkg/events.(*Events).batchWorker(0x10191fba0, {0x10143a878, 0x1400009ae80}, 0x0)
	/Users/creinhardt/go/pkg/mod/github.com/newrelic/newrelic-client-go/v2@v2.2.2/pkg/events/events_batch.go:170 +0x314
github.com/newrelic/newrelic-client-go/v2/pkg/events.(*Events).BatchMode.func2(0x14000243400?)
	/Users/creinhardt/go/pkg/mod/github.com/newrelic/newrelic-client-go/v2@v2.2.2/pkg/events/events_batch.go:44 +0x34
created by github.com/newrelic/newrelic-client-go/v2/pkg/events.(*Events).BatchMode
	/Users/creinhardt/go/pkg/mod/github.com/newrelic/newrelic-client-go/v2@v2.2.2/pkg/events/events_batch.go:43 +0x230
```

### Additional Context
The line in question is a trace logging line:
```e.logger.Trace("batchWorker[", id, "]: exiting per context Done")```
Probably just need to change that to 
```e.logger.Trace(fmt.Sprintf("batchWorker[%d]: exiting per context Done", id))```

**Comment by pranav-new-relic** [comment]
@ctriv I believe this should no longer be an issue, given these changes (https://github.com/newrelic/newrelic-client-go/pull/1104) which were recently merged to address the exact same issue. Closing the issue - thank you for reporting.
